### ISSUE TITLE
feat: fractional shares

### ISSUE THREAD

**Issue by matteoettam09** [crunchdao/backtest#27]
You do 
```python
quantity = int(holding_cash_value / price)
```

I would rather have the backtester support fractional shares and the asset allocator being responsible for providing the correct vector. Also, for a long-short product int() doesn't guarantee you are not overleveraged, so you might as well put at least np.round(), to be "close" to the provided value.

**Comment by Caceresenzo** [comment]
`int()` provide flooring behavior, which is intended as I do not want to buy an extra share which could cost a lot.
